package de.iman.jobApplication.model;

// Generated 14.05.2015 20:05:49 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Applications generated by hbm2java
 */
@Entity
@Table(name = "APPLICATIONS")
public class Applications implements java.io.Serializable {

	private int id;
	private JobDetails jobDetails;
	private UserDetails userDetails;
	private Date applyDate;
	private String result;

	public Applications() {
	}

	public Applications(int id, JobDetails jobDetails, UserDetails userDetails,
			Date applyDate) {
		this.id = id;
		this.jobDetails = jobDetails;
		this.userDetails = userDetails;
		this.applyDate = applyDate;
	}

	public Applications(int id, JobDetails jobDetails, UserDetails userDetails,
			Date applyDate, String result) {
		this.id = id;
		this.jobDetails = jobDetails;
		this.userDetails = userDetails;
		this.applyDate = applyDate;
		this.result = result;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "JOB_ID", nullable = false)
	public JobDetails getJobDetails() {
		return this.jobDetails;
	}

	public void setJobDetails(JobDetails jobDetails) {
		this.jobDetails = jobDetails;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ID", nullable = false)
	public UserDetails getUserDetails() {
		return this.userDetails;
	}

	public void setUserDetails(UserDetails userDetails) {
		this.userDetails = userDetails;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "APPLY_DATE", nullable = false, length = 19)
	public Date getApplyDate() {
		return this.applyDate;
	}

	public void setApplyDate(Date applyDate) {
		this.applyDate = applyDate;
	}

	@Column(name = "RESULT", length = 45)
	public String getResult() {
		return this.result;
	}

	public void setResult(String result) {
		this.result = result;
	}

}
