package de.iman.jobApplication.model;

// Generated 14.05.2015 20:05:49 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CompDetails generated by hbm2java
 */
@Entity
@Table(name = "COMP_DETAILS")
public class CompDetails implements java.io.Serializable {

	private Integer compId;
	private String city;
	private int zipCode;
	private String compName;
	private String country;
	private Set<JobDetails> jobDetailses = new HashSet<JobDetails>(0);

	public CompDetails() {
	}

	public CompDetails(String city, int zipCode, String compName, String country) {
		this.city = city;
		this.zipCode = zipCode;
		this.compName = compName;
		this.country = country;
	}

	public CompDetails(String city, int zipCode, String compName,
			String country, Set<JobDetails> jobDetailses) {
		this.city = city;
		this.zipCode = zipCode;
		this.compName = compName;
		this.country = country;
		this.jobDetailses = jobDetailses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "COMP_ID", unique = true, nullable = false)
	public Integer getCompId() {
		return this.compId;
	}

	public void setCompId(Integer compId) {
		this.compId = compId;
	}

	@Column(name = "CITY", nullable = false, length = 20)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "ZIP_CODE", nullable = false)
	public int getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(int zipCode) {
		this.zipCode = zipCode;
	}

	@Column(name = "COMP_NAME", nullable = false, length = 50)
	public String getCompName() {
		return this.compName;
	}

	public void setCompName(String compName) {
		this.compName = compName;
	}

	@Column(name = "COUNTRY", nullable = false, length = 20)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "compDetails")
	public Set<JobDetails> getJobDetailses() {
		return this.jobDetailses;
	}

	public void setJobDetailses(Set<JobDetails> jobDetailses) {
		this.jobDetailses = jobDetailses;
	}

}
