package de.iman.jobApplication.model;

// Generated 14.05.2015 20:05:49 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * UserDetails generated by hbm2java
 */
@Entity
@Table(name = "user_details",uniqueConstraints = @UniqueConstraint(columnNames = "USERNAME"))
public class UserDetails implements java.io.Serializable {

	private Integer userId;
	private JobDetails jobDetails;
	private String username;
	private String password;
	private String name;
	private String birthdate;
	private Set<Applications> applicationses = new HashSet<Applications>(0);

	public UserDetails() {
	}

	public UserDetails(JobDetails jobDetails, String username, String password,
			String name, String birthdate) {
		this.jobDetails = jobDetails;
		this.username = username;
		this.password = password;
		this.name = name;
		this.birthdate = birthdate;
	}

	public UserDetails(JobDetails jobDetails, String username, String password,
			String name, String birthdate, Set<Applications> applicationses) {
		this.jobDetails = jobDetails;
		this.username = username;
		this.password = password;
		this.name = name;
		this.birthdate = birthdate;
		this.applicationses = applicationses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "USER_ID", unique = true, nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "JOB_ID", nullable = false)
	public JobDetails getJobDetails() {
		return this.jobDetails;
	}

	public void setJobDetails(JobDetails jobDetails) {
		this.jobDetails = jobDetails;
	}

	@Column(name = "USERNAME", unique = true, nullable = false, length = 30)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "PASSWORD", nullable = false, length = 30)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "NAME", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Birthdate", nullable = false, length = 45)
	public String getBirthdate() {
		return this.birthdate;
	}

	public void setBirthdate(String birthdate) {
		this.birthdate = birthdate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetails")
	public Set<Applications> getApplicationses() {
		return this.applicationses;
	}

	public void setApplicationses(Set<Applications> applicationses) {
		this.applicationses = applicationses;
	}

}
